import { useState } from "react";
import { twMerge } from "tailwind-merge";
import { AnimatePresence, motion } from "framer-motion";

const faqs = [
    {
        question: "Do I need to download or install any software to use this app?",
        answer:
            "No downloads or installations are required. The entire application runs seamlessly in your web browser, making it accessible anytime, anywhere—without the hassle of setup.",
    },
    {
        question: "Will my session be automatically saved once it ends?",
        answer:
            "No, sessions are not saved by default. You have full control—after your session ends, you’ll be given the option to review and choose whether or not to save it for future reference.",
    },
    {
        question: "Can I use this voice interaction app on my mobile device?",
        answer:
            "While the application may function on some mobile browsers, it is primarily optimized for desktop usage. For the best performance and full feature support, we recommend using a desktop or laptop device.",
    },
    {
        question: "Are the AI responses generated by a real artificial intelligence engine?",
        answer:
            "Yes, the responses are powered by simulated AI behavior. While not connected to a production AI model in this version, the system is designed to mimic real AI interactions for demonstration and development purposes.",
    },
];

export default function Faq() {
    const [selectedIndex, setSelectedIndex] = useState(0);
    return <section className="font-oswald">
        <div className="bg-gradient-to-b from-[#000000] via-[#2d004d] to-[#000000] py-20 ">

            <h2 className="text-6xl font-medium mt-6 text-center max-w-xl mx-auto text-white">
                Questions? We&apos;ve got{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-purple-200">answers</span>
            </h2>
            <div className="mt-12 flex flex-col gap-6 max-w-xl mx-auto">
                {faqs.map((faq, faqIndex) => (
                    <div
                        key={faq.answer}
                        className="bg-neutral-900 rounded-2xl border border-white/10 p-6"
                    >
                        <div
                            className="flex justify-between items-center"
                            onClick={() => setSelectedIndex(faqIndex)}
                        >
                            <h3 className="font-medium text-white">{faq.question}</h3>
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                className={twMerge(
                                    "feather feather-plus text-purple-400 flex-shrink-0 transition duration-300",
                                    selectedIndex === faqIndex &&
                                    "rotate-45"
                                )}
                            >
                                <line x1="12" y1="5" x2="12" y2="19"></line>
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                            </svg>
                        </div>
                        <AnimatePresence>
                            {selectedIndex === faqIndex && (
                                <motion.div
                                    initial={{
                                        height: 0,
                                        marginTop: 0,
                                    }}
                                    animate={{
                                        height: "auto",
                                        marginTop: 24,
                                    }}
                                    exit={{
                                        height: 0,
                                        marginTop: 0,
                                    }}
                                    className={"overflow-hidden"}
                                >
                                    <p className="text-gray-600 ">
                                        {faq.answer}
                                    </p>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                ))}
            </div>
        </div>
    </section>
}